// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCihEcFQR2nioFBRHsafpVEImGHh3lRUOQ',
    appId: '1:154003139332:web:8dd9d9c00b18a76a0d3e51',
    messagingSenderId: '154003139332',
    projectId: 'phone-auth-5e6bc',
    authDomain: 'phone-auth-5e6bc.firebaseapp.com',
    storageBucket: 'phone-auth-5e6bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiUsOxVzI0VBoCYrCp6zL0qJbY64YNAcE',
    appId: '1:154003139332:android:b58b61e46c02c97d0d3e51',
    messagingSenderId: '154003139332',
    projectId: 'phone-auth-5e6bc',
    storageBucket: 'phone-auth-5e6bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGiihrQV27e6GFjMbpe3WVffgslXtOLWE',
    appId: '1:154003139332:ios:6ca5adba63854d760d3e51',
    messagingSenderId: '154003139332',
    projectId: 'phone-auth-5e6bc',
    storageBucket: 'phone-auth-5e6bc.appspot.com',
    androidClientId: '154003139332-f4a9b8lvb0ostb21prmvedsaucvn8k2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.quantumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGiihrQV27e6GFjMbpe3WVffgslXtOLWE',
    appId: '1:154003139332:ios:6ca5adba63854d760d3e51',
    messagingSenderId: '154003139332',
    projectId: 'phone-auth-5e6bc',
    storageBucket: 'phone-auth-5e6bc.appspot.com',
    androidClientId: '154003139332-f4a9b8lvb0ostb21prmvedsaucvn8k2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.quantumApp',
  );
}
